name: C/C++ CI

on:
  push:
    branches: [ master develop ]
  pull_request:
    branches: [ master develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: generate
      run: mkdir _build
      run: cmake -S . -B ./_build
    - name: build
      run: cmake --build ./_build
